var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var Account = require('./routes/Account.route.js');
var Address = require('./routes/Address.route.js');
var BillingAddress = require('./routes/BillingAddress.route.js');
var CompanyAddress = require('./routes/CompanyAddress.route.js');
var CreditLine = require('./routes/CreditLine.route.js');
var Currency = require('./routes/Currency.route.js');
var Customer = require('./routes/Customer.route.js');
var CustomsDetails = require('./routes/CustomsDetails.route.js');
var CustomsInformation = require('./routes/CustomsInformation.route.js');
var DebitLine = require('./routes/DebitLine.route.js');
var DocumentStatus = require('./routes/DocumentStatus.route.js');
var DocumentsTotals = require('./routes/DocumentsTotals.route.js');
var GeneralLedgerAccounts = require('./routes/GeneralLedgerAccounts.route.js');
var GeneralLedgerEntries = require('./routes/GeneralLedgerEntries.route.js');
var Header = require('./routes/Header.route.js');
var Invoice = require('./routes/Invoice.route.js');
var Journal = require('./routes/Journal.route.js');
var Line = require('./routes/Line.route.js');
var LinePay = require('./routes/LinePay.route.js');
var Lines = require('./routes/Lines.route.js');
var MasterFiles = require('./routes/MasterFiles.route.js');
var MovementOfGoods = require('./routes/MovementOfGoods.route.js');
var OrderReferences = require('./routes/OrderReferences.route.js');
var Payment = require('./routes/Payment.route.js');
var PaymentDT = require('./routes/PaymentDT.route.js');
var PaymentMethod = require('./routes/PaymentMethod.route.js');
var Payments = require('./routes/Payments.route.js');
var Product = require('./routes/Product.route.js');
var ProductSerialNumber = require('./routes/ProductSerialNumber.route.js');
var References = require('./routes/References.route.js');
var SalesInvoice = require('./routes/SalesInvoice.route.js');
var Settlement = require('./routes/Settlement.route.js');
var ShipFrom = require('./routes/ShipFrom.route.js');
var ShipTo = require('./routes/ShipTo.route.js');
var ShipToAddress = require('./routes/ShipToAddress.route.js');
var ShipFromAddress = require('./routes/ShipFrom.route.js');
var SourceDocuments = require('./routes/SourceDocuments.route.js');
var SourceDocumentID = require('./routes/SourceDocumentID.route.js');
var SpecialRegimes = require('./routes/SpecialRegimes.route.js');
var StockMovement = require('./routes/StockMovement.route.js');
var Supplier = require('./routes/Supplier.route.js');
var Tax = require('./routes/Tax.route.js');
var TaxTable = require('./routes/TaxTable.route.js');
var TaxTableEntry = require('./routes/TaxTableEntry.route.js');
var Transaction = require('./routes/Transaction.route.js');
var WithholdingTax = require('./routes/WithholdingTax.route.js');
var WorkDocument = require('./routes/WorkDocument.route.js');
var WorkingDocuments = require('./routes/WorkingDocuments.route.js');
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.connect('mongodb://localhost:27017/saft')
.then(()=> console.log('connection succesful'))
.catch((err) => console.error(err));

var app = express();

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/users', usersRouter);

app.use('/account', Account);
app.use('/address', Address);
app.use('/billingAddress', BillingAddress);
app.use('/companyAddress', CompanyAddress);
app.use('/creditLine', CreditLine);
app.use('/currency', Currency);
app.use('/customer', Customer);
app.use('/customsDetails', CustomsDetails);
app.use('/customsInformation', CustomsInformation);
app.use('/debitLine', DebitLine);
app.use('/documentStatus', DocumentStatus);
app.use('/documentsTotals', DocumentsTotals);
app.use('/generalLedgerAccounts', GeneralLedgerAccounts);
app.use('/generalLedgerEntries', GeneralLedgerEntries);
app.use('/header', Header);
app.use('/invoice', Invoice);
app.use('/journal', Journal);
app.use('/line', Line);
app.use('/linePay', LinePay);
app.use('/lines', Lines);
app.use('/movementOfGoods', MovementOfGoods);
app.use('/orderReferences', OrderReferences);
app.use('/payment', Payment);
app.use('/paymentDT', PaymentDT);
app.use('/paymentMethod', PaymentMethod);
app.use('/payments', Payments);
app.use('/product', Product);
app.use('/productSerialNumber', ProductSerialNumber);
app.use('/references', References);
app.use('/salesInvoice', SalesInvoice);
app.use('/settlement', Settlement);
app.use('/shipFrom', ShipFrom);
app.use('/shipTo', ShipTo);
app.use('/shipToAddress', ShipToAddress);
app.use('/shipFromAddress', ShipFromAddress);
app.use('/sourceDocuments', SourceDocuments);
app.use('/sourceDocumentID', SourceDocumentID);
app.use('/specialRegimes', SpecialRegimes);
app.use('/stockMovement', StockMovement);
app.use('/supplier', Supplier);
app.use('/tax', Tax);
app.use('/taxTable', TaxTable);
app.use('/taxTableEntry', TaxTableEntry);
app.use('/transaction', Transaction);
app.use('/withholdingTax', WithholdingTax);
app.use('/workDocument', WorkDocument);
app.use('/workingDocuments', WorkingDocuments);


module.exports = app;
